using UnityEngine;

public class AdvancedGhostVisualizaton : MonoBehaviour
{
	public enum Effect
	{
		Attack = 0,
		Die = 1,
		Respawn = 2,
		None = 3
	}

	private abstract class EffectBase
	{
		protected float duration;

		protected float timeLeft;

		protected abstract void UpdateEffect(AdvancedGhostVisualizaton ghostVisualizaton);

		public abstract void Exit(AdvancedGhostVisualizaton ghost);

		protected EffectBase(float duration)
		{
		}

		public bool Update(AdvancedGhostVisualizaton ghostVisualizaton)
		{
			return false;
		}
	}

	private class Die : EffectBase
	{
		public Die(float duration, AdvancedGhostVisualizaton ghostVisualizaton)
			: base(0f)
		{
		}

		protected override void UpdateEffect(AdvancedGhostVisualizaton ghostVisualizaton)
		{
		}

		private Vector3 UpdateScale(AdvancedGhostVisualizaton ghostVisualizaton)
		{
			return default(Vector3);
		}

		public override void Exit(AdvancedGhostVisualizaton ghost)
		{
		}
	}

	private class Respawn : EffectBase
	{
		public Respawn(float duration, AdvancedGhostVisualizaton ghostVisualizaton)
			: base(0f)
		{
		}

		protected override void UpdateEffect(AdvancedGhostVisualizaton ghostVisualizaton)
		{
		}

		private Vector3 UpdateScale(AdvancedGhostVisualizaton ghostVisualizaton)
		{
			return default(Vector3);
		}

		public override void Exit(AdvancedGhostVisualizaton ghost)
		{
		}
	}

	private EffectBase currentEffect;

	private Vector3 baseScale;

	public GhostEye ghostEye;

	public GhostBody ghostBody;

	public AdvancedGhostBlinker blinker;

	public AudioSource moving;

	public AudioSource receiveDamage;

	public AudioSource weaponHitSound;

	private void Awake()
	{
	}

	public void SetRotationSpeed(float rotationSpeed)
	{
	}

	public void ReceivedDamage()
	{
	}

	public void ReceivedHealing()
	{
	}

	public void PlayEffect(Effect effect, float duration)
	{
	}

	private void Update()
	{
	}

	private void Start()
	{
	}

	private void OnEnable()
	{
	}

	private void OnDisable()
	{
	}
}
